### ISSUE TITLE
versions and colors keywords not working with PlantUML 1.2019.07

### ISSUE THREAD

**Issue by studgeek** [esteinberg/plantuml4idea#227]
FYI, I tried upgrading to PlantUML 1.2019.07 by switching jars. It works fine for the drawings I tested, but fails for keywords like versions and colors.

Plugin version is 2.17.3. 

IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 27, 2019
Licensed to Google

JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

Stacks below:

```
Failed to render image @startuml
colors
' colors WhiteSmoke
@enduml

java.lang.NoClassDefFoundError: net/sourceforge/plantuml/PSystemError
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.getTitles(PlantUmlRendererUtil.java:187)
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.zoomDiagram(PlantUmlRendererUtil.java:105)
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.doRender(PlantUmlNormalRenderer.java:98)
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.render(PlantUmlRendererUtil.java:73)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:66)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
Failed to render image @startuml
version
@enduml

java.lang.NoClassDefFoundError: net/sourceforge/plantuml/PSystemError
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.getTitles(PlantUmlRendererUtil.java:187)
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.zoomDiagram(PlantUmlRendererUtil.java:105)
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.doRender(PlantUmlNormalRenderer.java:98)
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.render(PlantUmlRendererUtil.java:73)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:66)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by krasa** [comment]
you can update

**Comment by studgeek** [comment]
Confirmed version and colors working with 2.18.1 which includes plantuml 1.2019.07. Thanks for quick response!
